---
- hosts: helios
  user: grambo
  sudo: yes
  tasks:
  - name: Update apt-cache
    apt: update_cache=yes
  
  - name: Install packages via apt
    apt: pkg=$item 
    with_items:
        - nginx
        - mysql-server-5.1
        - php5
        - build-essential
        - python-dev
        - libxml2-dev

  - name: Install python packages via pip
    pip: name=$item
    with_items:
        - virtualenv
        - uwsgi

  - name: Disable default nginx virtual host
    file: name=/etc/nginx/sites-enabled/default state=absent

  - include: includes/virtualhost.yml 
    vars:
        vhost: blog 
        address: blog.grambo.me.uk
        caching: true
  - include: includes/virtualhost.yml
    vars:
        vhost: cpp11 
        address: cpp11.grambo.me.uk
        caching: true
  
  handlers:
  - name: restart nginx
    action: service name=nginx state=restarted


