---
- hosts: helios
  user: grambo
  sudo: yes
  tasks:
  - name: Update apt-cache
    apt: update_cache=yes
  
  - name: Ensure nginx present
    apt: pkg=nginx 
  - name: Ensure mysql (boo) present
    apt: pkg=mysql-server-5.1
  - name: Ensure php (boo) present
    apt: pkg=php5
  - name: Ensure build-essential present
    apt: pkg=build-essential
  - name: Ensure python-dev present
    apt: pkg=python-dev
  - name: Ensure libxml2-dev present
    apt: pkg=libxml2-dev

  - name: Ensure virtualenv present
    pip: name=virtualenv
  - name: Ensure uwsgi present
    pip: name=uwsgi
